
class Status:
    STATUS1 = "EXECUTION NOT STARTED YET"
    STATUS2 = "JOB TITLE MUST NOT BE EMPTY"
    STATUS3 = "JOB TITLE CANNOT BE A NUMBER ONLY"
    STATUS4 = "SEARCH QUANTITY BOX MUST NOT BE EMPTY"
    STATUS5 = "SEARCH QUANTITY BOX CONTAINS ALPHABETS TOO"
    STATUS6 = "EXECUTION STARTED"
    STATUS7 = "NAVIGATED TO PK.INDEED.COM SUCCESSFULLY"
    STATUS8 = "INSERTING JOB TITLE: '{0}'"
    STATUS9 = "INSERTING JOB LOCATION: '{0}'"
    STATUS10 = "STARTED SEARCHING"
    STATUS11 = "TOTAL JOBS FOUND: {0}"
    STATUS12 = "TOTAL JOBS SCRAPED SO FAR: {0}"
    STATUS13 = "TOTAL JOBS SCRAPED: {0} EQUAL TO YOUR DESIRED QUANTITY: {1}"
    STATUS14 = "TOTAL JOBS SCRAPED: {0} DISCARDING ADDITIONAL {1} JOBS"
    STATUS15 = "NAVIGATING TO NEXT PAGE FOR SCRAPING FURTHER"
    STATUS16 = "NO MORE PAGES FURTHER TO SCRAP"
    STATUS17 = "NO DATA AVAILABLE ON SCREEN"
    STATUS18 = "FILE SAVED"
    STATUS19 = "SUCCESSFULLY SCRAPPED THE WEBSITE!!!"
    STATUS20 = "PREPARING THE SCRAPPED DATA"

class Warning:
    WARNING1 = "NO JOBS FOUND"
    WARNING2 = "JOB TITLE MUST NOT BE EMPTY"
    WARNING3 = "JOB TITLE CANNOT BE A NUMBER ONLY"

class Error:
    ERROR1 = "UNEXPECTED ERROR OCCUR, TRY AGAIN"
    ERROR2 = "NO DATA SCRAPPED"
    ERROR3 = "NO FILE PATH WERE GIVEN, FILE DISCARDED"